use_frameworks!
pod 'Lookback', :configurations => ['Debug']
pod 'LookbackSafe', :configurations => ['Release']
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Google/Analytics'
pod 'HanekeSwift'

